version: '3.9'

services:
  db:
    image: postgres:16-alpine
    container_name: cf-lapa-db
    environment:
      POSTGRES_DB: cflapa
      POSTGRES_USER: cflapa
      POSTGRES_PASSWORD: cflapa
      POSTGRES_INITDB_ARGS: ""
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cflapa -d cflapa"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default

volumes:
  pgdata:
    driver: local
